# ===============================
# SERVER CONFIGURATION (Node1 - ANBA)
# ===============================

server.port=8081
server.address=0.0.0.0
spring.application.name=distributed-student-system


# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# LOGGING CONFIGURATION
# ===============================

logging.level.org.springframework=INFO
logging.level.com.student.records=DEBUG


# ===============================
# DISTRIBUTED SYSTEM CONFIGURATION
# ===============================

node.id=node1
cluster.nodes=http://10.48.29.58:8081,http://10.48.29.166:8082,http://10.48.29.228:8083
